services:
  lbc-finder:
    build: .
    container_name: lbc-finder
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - DB_PATH=/app/data/leboncoin_ads.db
      - PORT=5000
    restart: unless-stopped
